-- Step 1: Create the clean table with all transformations
SELECT DISTINCT 
    "ORDERNUMBER", "QUANTITYORDERED", "PRICEEACH", "ORDERLINENUMBER",
    "SALES", "QTR_ID", "MONTH_ID", "YEAR_ID", "MSRP",
    UPPER(TRIM("PRODUCTCODE")) AS "PRODUCTCODE",
    UPPER(TRIM("PRODUCTLINE")) AS "PRODUCTLINE",
    UPPER(TRIM("STATUS")) AS "STATUS",
    UPPER(TRIM("CUSTOMERNAME")) AS "CUSTOMERNAME",
    UPPER(TRIM("CONTACTFIRSTNAME")) AS "CONTACTFIRSTNAME",
    UPPER(TRIM("CONTACTLASTNAME")) AS "CONTACTLASTNAME",
    UPPER(TRIM("CITY")) AS "CITY",
    UPPER(TRIM("COUNTRY")) AS "COUNTRY",
    UPPER(TRIM("DEALSIZE")) AS "DEALSIZE",
    UPPER(TRIM("ADDRESSLINE1")) AS "ADDRESSLINE1",
    UPPER(TRIM("PHONE")) AS "PHONE",
    
    -- Handling empty strings and nulls using NULLIF and COALESCE
    -- This ensures Python will see NO missing values
    UPPER(TRIM(COALESCE(NULLIF("POSTALCODE", ''), 'N/A'))) AS "POSTALCODE",
    UPPER(TRIM(COALESCE(NULLIF("ADDRESSLINE2", ''), 'NONE'))) AS "ADDRESSLINE2",
    UPPER(TRIM(COALESCE(NULLIF("STATE", ''), 'UNKNOWN'))) AS "STATE",
    UPPER(TRIM(COALESCE(NULLIF("TERRITORY", ''), 'NONE'))) AS "TERRITORY",

    TO_DATE("ORDERDATE", 'MM/DD/YYYY') AS "ORDERDATE"

INTO sales_clean 
FROM sales
WHERE "SALES" > 0;